- name: restart consul
  service: name=consul state=restarted

- name: restart dnsmasq
  service: name=dnsmasq state=restarted
  notify: restart registrator

- name: restart registrator
  service: name=registrator state=restarted

- name: run resolvconf
  shell: resolvconf -u
